services:
  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data
    ports:
      - '6379:6379'
